<?php
 /* Saved by FileDatabase */
?><?php
 /* code generated by FileDatabase */
?><?php
$config = new Config();

$config -> set_web_title ('My Web');
$config -> set_web_description ('This is just my web, no big deal');
$config -> set_web_keywords ('web, my, presentation, nanotube');
$config -> set_mysql_server ('localhost');
$config -> set_mysql_database ('nanotube');
$config -> set_mysql_user ('nanotube_db_user');
$config -> set_mysql_password ('his_mysql_nano_password');
$config -> set_na_password ('1ede6e89cb7e1ab0f15a43d9ca9b27d142702da7');
$config -> set_na_password_salt ('t62z33t75x69t32x77z16r53v44u71y85w90v71u83s36z02s45v19q63w67v10s72y81q94y00w63x24r08x09z50');

return $config;

?>