<?php /* Saved by FileDatabase */ ?>
<?php /* code generated by FileDatabase */ ?>
<?php
$config = new Config();

$config -> set_web_title ('Můj web');
$config -> set_web_description ('Tohle je můj web');
$config -> set_web_keywords ('můj, soubkromý,web');
$config -> set_mysql_server ('localhost');
$config -> set_mysql_database ('nanotube_dev');
$config -> set_mysql_user ('nanotube_db_user');
$config -> set_mysql_password ('his_nano_password');

return $config;
?>
