<?php /* Saved by FileDatabase */ ?>
<?php /* code generated by FileDatabase */ ?>
<?php
$config = new Config();

$config -> set_web_title ('My webby');
$config -> set_web_description ('Tohle je můj web');
$config -> set_web_keywords ('můj, soukromý,web');
$config -> set_mysql_server ('localhost');
$config -> set_mysql_database ('nanotube_dev');
$config -> set_mysql_user ('nanotube_db_user');
$config -> set_mysql_password ('his_nano_password');
$config -> set_na_password (null);
$config -> set_na_password_salt (null);
$config -> set_links_format ('?site=SITE_ID');

return $config;
?>
